<%@ Page Language="VB" AutoEventWireup="false" CodeFile="sqltest_VerificaTabletFirma.aspx.vb" Inherits="sqltest2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<meta http-equiv="refresh" content="300"/>  <%--refresh ogni 10 minuti  / test ogni 2 --%>

    <title></title>
    <script language="javascript" type="text/javascript">
        
    </script>
</head>
<body>
    <form id="form1" runat="server">

        <div>
            Precedente refresh: <asp:Label ID="lbl_last" runat="server" Text=""></asp:Label>
        </div>
        <div>
            Precedente Ultimo Contratto: <asp:Label ID="lbl_last_ra" runat="server" Text=""></asp:Label>
        </div>

        
        <br />
        
        <div>
            <asp:Button ID="LginAccedi" runat="server" BackColor="#FFFBFF" BorderColor="#CCCCCC" 
        BorderStyle="Solid" BorderWidth="1px" Font-Names="Verdana" OnClick="LginAccedi_Click"
        Font-Size="1em" ForeColor="#284775" Text="Visualizza" />
    
        </div>
        
    


        <br />


        
        <div>
                       

               <asp:GridView ID="gridview1" runat="server" CellPadding="4" EmptyDataText="- Nessuna dato -"  
        ForeColor="#003366" GridLines="None" Font-Names="Verdana" Font-Size="12px" HorizontalAlign="left" HeaderStyle-Height="20" 
        HeaderStyle-HorizontalAlign="left" HeaderStyle-VerticalAlign="Top" EnableModelValidation="True" 
            CellSpacing="2"  AllowPaging="false" PageSize="200" AutoGenerateColumns="true" AutoGenerateEditButton="false" DataKeyNames="id"
             AutoGenerateDeleteButton ="false" DataSourceID="SqlDataSource1" >

            <AlternatingRowStyle BackColor="White" />
            <EditRowStyle BackColor="#F2F2F2"/>
            <FooterStyle BackColor="Silver" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#052e58" Font-Bold="True" ForeColor="White" CssClass="ucase" />
            <PagerStyle BackColor="#D1DDF1" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#e6f4fb" />
            <SelectedRowStyle BackColor="#D1DDF1"  ForeColor="#333333" />

            </asp:GridView>


            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SicilyConnectionString %>" 
             ></asp:SqlDataSource>


        </div>
        <br />

       
    </form>
</body>
</html>
