<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPageNoMenuNoFooter.master"  AutoEventWireup="true" 
   MaintainScrollPositionOnPostback="true" CodeFile="table_update.aspx.vb" Inherits="vbcode" %>

<asp:Content runat="server" ID="co1" ContentPlaceHolderID="ContentPlaceHolder1">


<div style="margin-top:30px;">
        <asp:Label ID="lbl_1" runat="server" Text="Tabella Condizioni Righe Costi Periodi" Font-Bold="true" Font-Size="Medium"></asp:Label>
        &nbsp;&nbsp;&nbsp
        <asp:Label ID="lbl_error" runat="server" Text="" Font-Bold="true" Font-Size="Medium" ForeColor="Red" Visible="true"></asp:Label>
</div>

<div style="text-align :left;height:auto;">
                                                                                       
        <asp:GridView ID="grid1" runat="server"   CellPadding="6" EmptyDataText="- Nessun record presente -"  CssClass="gridw"
        ForeColor="#003366" GridLines="None" Font-Names="Verdana" Font-Size="12px" HorizontalAlign="left" HeaderStyle-Height="30" 
        HeaderStyle-HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle" EnableModelValidation="True" 
        CellSpacing="8"  AllowPaging="false" PageSize="50" AutoGenerateColumns="false" AutoGenerateEditButton="true" 
        DataKeyNames="ID" AutoGenerateDeleteButton ="false" DataSourceID="sqldatasource1" OnRowDataBound="grid1_RowDataBound" 
            OnRowEditing="grid1_RowEditing" OnRowUpdating="grid1_RowUpdating" OnRowCancelingEdit="grid1_RowCancelingEdit"  >

        <AlternatingRowStyle BackColor="LightGray"  />
        <EditRowStyle BackColor="#F2F2F2" Font-Bold="True"/>
        <FooterStyle BackColor="Silver" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#336699" Font-Bold="True" ForeColor="White" CssClass="ucase" Height="20"/>
        <PagerStyle BackColor="#D1DDF1" ForeColor="#333333" HorizontalAlign="Center" Font-Size="Medium" Font-Bold="true" />
        <RowStyle BackColor="White" Height="24" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                              
       <Columns>

               <%-- <asp:BoundField DataField="ID_IC" HeaderText="ID"  ReadOnly="True" Visible="true" ItemStyle-Font-Bold="true" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center"/>
          --%>
              <%--  <asp:BoundField  DataField="Tipo_indice" HeaderText="Tipo"   ItemStyle-Font-Bold="false" 
                    ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" />--%>

               <%-- <asp:BoundField  DataField="op1" HeaderText="Operatore 1"  ItemStyle-HorizontalAlign="Center"  />
                <asp:BoundField  DataField="val1" HeaderText="Valore 1"  ItemStyle-HorizontalAlign="Center"  />--%>
                 <%--<asp:BoundField  DataField="confronto" HeaderText="Confronto"  ItemStyle-HorizontalAlign="Center"  />--%>
               <%-- <asp:BoundField  DataField="op2" HeaderText="Operatore 2"  ItemStyle-HorizontalAlign="Center"  />--%>
                <%--<asp:BoundField  DataField="val2" HeaderText="Valore 2"  ItemStyle-HorizontalAlign="Center"  />--%>
                <%--<asp:BoundField  DataField="rif_grafico" HeaderText="Rif. Grafico" ItemStyle-HorizontalAlign="Center"  />--%>


                <asp:TemplateField  HeaderText="ID">
                     <ItemTemplate>
                       <%# Eval("ID") %>                     
                     
                     </ItemTemplate>                    
                         <ItemStyle Width="40px" />
                 </asp:TemplateField>

                <asp:TemplateField  HeaderText="ID Elemento">
                     <ItemTemplate>                         
                     <asp:Label ID="lbl_id_elemento" runat="server" Text='<%# Eval("id_elemento") %>' ></asp:Label>                 
                     </ItemTemplate>                    
                         <ItemStyle Width="60px" HorizontalAlign="Center" />
                 </asp:TemplateField>



                 <asp:TemplateField  HeaderText="Elemento">
                     <ItemTemplate>                      
                         <asp:Label ID="lbl_descrizione" runat="server" Text='<%# Eval("descrizione") %>'></asp:Label>                
                      </ItemTemplate>
                         <ItemStyle Width="200px" HorizontalAlign="center" />
                 </asp:TemplateField>
                

                  <asp:TemplateField  HeaderText="Data Pick-UP">
                     <ItemTemplate>
                                           
                          <asp:Label ID="txt_data_pickup" runat="server" Text='<%# Eval("data_pickup") %>'></asp:Label>                

                      </ItemTemplate>
                     <EditItemTemplate>
                           <asp:TextBox ID="txt_data_pickup" runat="server" width="80px" Text='<%#Bind("data_pickup")%>'/>
                           
                         <asp:CompareValidator
                                    id="dateValidator" runat="server" 
                                    Type="Date"
                                    Operator="DataTypeCheck" Display="Dynamic"
                                    ControlToValidate="txt_data_pickup" 
                                    ErrorMessage="<br/>Formato data errato gg/mm/aaaa">
                                </asp:CompareValidator>                   
                    
                       </EditItemTemplate>
                         <ItemStyle Width="150px" HorizontalAlign="center"/>
                 </asp:TemplateField>
                    
                  <asp:TemplateField  HeaderText="Applicabilità Da">
                     <ItemTemplate>
                         <asp:Label ID="txt_applicabilita_da" runat="server" Text='<%# Bind("applicabilita_da") %>'></asp:Label>                                     
                      </ItemTemplate>
                     <EditItemTemplate>
                           <asp:TextBox ID="txt_applicabilita_da" runat="server" width="80px" Text='<%# Bind("applicabilita_da") %>' />                             
                          <asp:RangeValidator 
                             id="rangevalda" 
                             ControlToValidate="txt_applicabilita_da" 
                             MinimumValue="0"
                             MaximumValue="999" 
                             Type="Integer"  
                             ErrorMessage="<br/>Valore compreso tra 0 e 999"                             
                              text=""
                              Display="Dynamic"
                             ForeColor="red"                              
                             runat="server" >
                        </asp:RangeValidator>            
                         
                     </EditItemTemplate>
                         <ItemStyle Width="120px" HorizontalAlign="center"/>
                      
                 </asp:TemplateField>
                  
                         <asp:TemplateField  HeaderText="Applicabilità A">
                     <ItemTemplate>
                         <asp:Label ID="txt_applicabilita_a" runat="server" Text='<%# Bind("applicabilita_a") %>'></asp:Label>                          
                      </ItemTemplate>
                     <EditItemTemplate>
                           <asp:TextBox ID="txt_applicabilita_a" runat="server" width="80px" Text='<%# Bind("applicabilita_a") %>'/>                             
                        <asp:RangeValidator 
                             id="rangeval" 
                             ControlToValidate="txt_applicabilita_a" 
                             MinimumValue="0"
                             MaximumValue="999" 
                             Type="Integer"  
                             ErrorMessage="<br/>Valore compreso tra 0 e 999"                             
                            text=""
                            Display="Dynamic"
                             ForeColor="red"                              
                             runat="server" >
                        </asp:RangeValidator>            
                      
                         
                     </EditItemTemplate>
                         <ItemStyle Width="100px" HorizontalAlign="center"/>
                 </asp:TemplateField>   
           
           
                    <asp:TemplateField  HeaderText="Costo €">
                     <ItemTemplate>
                           <asp:Label ID="txt_costo" runat="server" Text='<%#Eval("costo") %>'></asp:Label>  
                                        
                      </ItemTemplate>
                     <EditItemTemplate>
                           <asp:TextBox ID="txt_costo" runat="server" width="80px" Text='<%# Bind("costo") %>'/>     
                           <asp:CompareValidator
                                    id="numberValidator" runat="server" 
                                    Type="Double" 
                                    Operator="DataTypeCheck" Display="Dynamic"
                                    ControlToValidate="txt_costo" 
                                    ErrorMessage="<br/>Formato importo errato">
                                </asp:CompareValidator>                  

                       </EditItemTemplate>
                         <ItemStyle Width="80px" HorizontalAlign="center"/>
                 </asp:TemplateField>
           

            </Columns>

                  
</asp:GridView>

        <asp:SqlDataSource ID="sqldatasource1" runat="server" ConnectionString="<%$ ConnectionStrings:SicilyConnectionString %>"  >    
    </asp:SqlDataSource>

  <asp:SqlDataSource ID="sqldatasource2" runat="server" ConnectionString="<%$ ConnectionStrings:SicilyConnectionString %>"  >    
    </asp:SqlDataSource>

   
                     



    </div>
                   
     
    </asp:Content>